# DATA
dataset_path: "nave1616/landcover-urban-climate"

# VISUALIZATION
figuredirectory: reports/figures/
project:
  models_dir: models
  pretrained_dir: models/pretrained_models
  logs_dir: models/logs
  results_dir: results

training:
  batch_size: 32
  max_epochs: 50
  learning_rate: 2e-5
  num_workers: 4
  model_name: b0
  patience: 10
