# DATA
dataset:
  dataset_path: "erikpinhasov/landcover_dataset"
  id2label:
    0: "background"
    1: "bareland"
    2: "rangeland"
    3: "developed space"
    4: "road"
    5: "tree"
    6: "water"
    7: "agriculture land"
    8: "buildings"

# PROJECT DIRECTORIES
directories:
  models: models
  pretrained: models/pretrained_models
  logs: models/logs
  checkpoints: models/logs/checkpoints
  results: results

# TRAINING SETTINGS
training:
  model_name: b0
  batch_size: 16
  max_epochs: 50
  num_workers: 8
  learning_rate: 2e-5
  weight_decay: 1e-3

# CALLBACKS SETTINGS
callbacks:
  early_stop:
    patience: 5
    monitor: "val_loss"
    mode: "min"
  save_model:
    monitor: "val_mean_iou"
    mode: "max"

# LOSS SETTINGS
loss:
  ignore_index: 0 # int | None
  weighting_strategy: "raw" # Options: "none", "balanced", "max", "sum", or "raw"
  alpha: 0.7
  beta: 0.3
