# DATA
dataset:
  dataset_path: "erikpinhasov/landcover_dataset"
  id2label:
    0: "background"
    1: "bareland"
    2: "rangeland"
    3: "developed space"
    4: "road"
    5: "tree"
    6: "water"
    7: "agriculture land"
    8: "buildings"

# PROJECT DIRECTORIES
directories:
  models: models
  pretrained: models/pretrained_models
  logs: models/logs
  checkpoints: models/logs/checkpoints
  results: results

# TRAINING SETTINGS
training:
  model_name: b0
  batch_size: 32
  max_epochs: 50
  num_workers: 8
  learning_rate: 2e-5
  dropout: 0.2
  weight_decay: 1e-4
  early_stop:
    patience: 5

# LOSS SETTINGS
loss:
  ignore_index: 0
  weights: True # Use class weights
  normalize: "none" # Options: balanced, max, sum, none
  alpha: 0.5
  beta: 0.5
