# DATA
dataset_path: "nave1616/landcover_dataset"

project:
  models_dir: models
  pretrained_dir: models/pretrained_models
  logs_dir: models/logs
  results_dir: results

training:
  batch_size: 32
  max_epochs: 50
  num_workers: 4
  log_every_n_steps: 10
  learning_rate: 2e-5
  model_name: b1

  early_stop:
    patience: 10

  focal_loss:
    gamma: 2
    do_class_weight: True
    normalize_weight: True
    ignore_index: None
