# DATA
dataset_path: "erikpinhasov/landcover_urban_climate"

# VISUALIZATION
figuredirectory: reports/figures/
project:
  models_dir: models
  pretrained_dir: models/pretrained_models
  logs_dir: models/logs
  results_dir: results

training:
  batch_size: 32
  max_epochs: 50
  learning_rate: 2e-5
  num_workers: 4
  model_name: b1
  patience: 10
  log_every_n_steps: 10
  do_class_weight: True
