[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_microclimate"
version = "0.1.0"
description = "Machine Learning Microclimate Prediction Project"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }

dependencies = [
    "albucore==0.0.16",
    "albumentations==1.4.15",
    "datasets==3.0.0",
    "matplotlib==3.9.2",
    "pytorch-lightning==2.4.0",
    "scikit-learn==1.5.2",
    "torch==2.4.1",
    "torchmetrics==1.4.2",
    "tqdm==4.66.5",
    "transformers==4.44.2",
    "tensorboardX==2.6.2.2",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]


[project.optional-dependencies]
dev = ["pre-commit", "black", "flake8", "pytest", "pytest-mock"]

[project.scripts]
ml = "scripts.main:main"

[tool.coverage.run]
source = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

# Suppress all UserWarning messages
filterwarnings = ["ignore::UserWarning"]

# Add coverage options and specify which module to measure coverage for
addopts = "--cov=src --cov-report=term-missing"
