[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_microclimate"
version = "0.1.0"
description = "Machine Learning Microclimate Prediction Project"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
dependencies = [
    "torch>=1.8.0",
    "pytorch-lightning",
    "transformers>=4.0.0",
    "albumentations>=0.5.0",
    "datasets>=1.6.0",
    "torchmetrics>=0.5.0",
    "evaluate>=0.1.0",
    "tqdm>=4.41.0",
    "scikit-learn",
    "huggingface_hub",
    "albucore==0.0.16",
    "matplotlib",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]


[project.optional-dependencies]
dev = ["pre-commit", "black", "flake8"]

[project.scripts]
ml = "scripts.main:main"
